// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YksHocamAPI.Models;

#nullable disable

namespace YksHocamAPI.Migrations
{
    [DbContext(typeof(YksHocamDbContext))]
    [Migration("20251223120045_ProjeSifirKurulum")]
    partial class ProjeSifirKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YksHocamAPI.Models.AliskanlikGunleri", b =>
                {
                    b.Property<int>("ZincirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZincirId"));

                    b.Property<int?>("AliskanlikId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ZincirId")
                        .HasName("PK__Aliskanl__3E2FF6CEF98B9905");

                    b.HasIndex("AliskanlikId");

                    b.ToTable("AliskanlikGunleri", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.Aliskanliklar", b =>
                {
                    b.Property<int>("AliskanlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AliskanlikId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AliskanlikId")
                        .HasName("PK__Aliskanl__01DBA92A5DEE72FC");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Aliskanliklar", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.Bildirimler", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimId"));

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("OkunduMu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BildirimId")
                        .HasName("PK__Bildirim__E778CE7E19021CF7");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Bildirimler", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.Dersler", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DersTip")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OgrenciAlan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DersId")
                        .HasName("PK__Dersler__E8B3DE110D318E04");

                    b.ToTable("Dersler", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.Konular", b =>
                {
                    b.Property<int>("KonuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KonuId"));

                    b.Property<int?>("DersId")
                        .HasColumnType("int");

                    b.Property<string>("KonuAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KonuId")
                        .HasName("PK__Konular__DA4F3424AF48711A");

                    b.HasIndex("DersId");

                    b.ToTable("Konular", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.KullaniciKonuTakip", b =>
                {
                    b.Property<int>("TakipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakipId"));

                    b.Property<int?>("KonuId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool?>("TamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("TakipId")
                        .HasName("PK__Kullanic__B19E07C7104A81B6");

                    b.HasIndex("KonuId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciKonuTakip", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.Kullanicilar", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProfilFotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KullaniciId")
                        .HasName("PK__Kullanic__E011F77B5ED1E05D");

                    b.HasIndex(new[] { "Email" }, "UQ__Kullanic__A9D10534DC669315")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.Notlar", b =>
                {
                    b.Property<int>("NotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotId"));

                    b.Property<string>("Alan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NotId")
                        .HasName("PK__Notlar__4FB2008A456175B3");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Notlar", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.OnemliGun", b =>
                {
                    b.Property<int>("OnemliGunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OnemliGunId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("RenkKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("OnemliGunId");

                    b.ToTable("OnemliGunler");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Planlar", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Saat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime");

                    b.HasKey("PlanId")
                        .HasName("PK__Planlar__755C22B744332759");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Planlar", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.PomodoroOturumlari", b =>
                {
                    b.Property<int>("OturumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OturumId"));

                    b.Property<string>("CalisilanKonu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("SureDakika")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("OturumId")
                        .HasName("PK__Pomodoro__59AA116D48698A6B");

                    b.HasIndex("KullaniciId");

                    b.ToTable("PomodoroOturumlari", (string)null);
                });

            modelBuilder.Entity("YksHocamAPI.Models.AliskanlikGunleri", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Aliskanliklar", "Aliskanlik")
                        .WithMany("AliskanlikGunleris")
                        .HasForeignKey("AliskanlikId")
                        .HasConstraintName("FK__Aliskanli__Alisk__66603565");

                    b.Navigation("Aliskanlik");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Aliskanliklar", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Kullanicilar", "Kullanici")
                        .WithMany("Aliskanliklars")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__Aliskanli__Kulla__628FA481");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Bildirimler", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Kullanicilar", "Kullanici")
                        .WithMany("Bildirimlers")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__Bildiriml__Kulla__6A30C649");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Konular", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Dersler", "Ders")
                        .WithMany("Konulars")
                        .HasForeignKey("DersId")
                        .HasConstraintName("FK__Konular__DersId__4F7CD00D");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("YksHocamAPI.Models.KullaniciKonuTakip", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Konular", "Konu")
                        .WithMany("KullaniciKonuTakips")
                        .HasForeignKey("KonuId")
                        .HasConstraintName("FK__Kullanici__KonuI__534D60F1");

                    b.HasOne("YksHocamAPI.Models.Kullanicilar", "Kullanici")
                        .WithMany("KullaniciKonuTakips")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__Kullanici__Kulla__52593CB8");

                    b.Navigation("Konu");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Notlar", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Kullanicilar", "Kullanici")
                        .WithMany("Notlars")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__Notlar__Kullanic__571DF1D5");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Planlar", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Kullanicilar", "Kullanici")
                        .WithMany("Planlars")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__Planlar__Kullani__5AEE82B9");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YksHocamAPI.Models.PomodoroOturumlari", b =>
                {
                    b.HasOne("YksHocamAPI.Models.Kullanicilar", "Kullanici")
                        .WithMany("PomodoroOturumlaris")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("FK__PomodoroO__Kulla__5EBF139D");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Aliskanliklar", b =>
                {
                    b.Navigation("AliskanlikGunleris");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Dersler", b =>
                {
                    b.Navigation("Konulars");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Konular", b =>
                {
                    b.Navigation("KullaniciKonuTakips");
                });

            modelBuilder.Entity("YksHocamAPI.Models.Kullanicilar", b =>
                {
                    b.Navigation("Aliskanliklars");

                    b.Navigation("Bildirimlers");

                    b.Navigation("KullaniciKonuTakips");

                    b.Navigation("Notlars");

                    b.Navigation("Planlars");

                    b.Navigation("PomodoroOturumlaris");
                });
#pragma warning restore 612, 618
        }
    }
}
